### ISSUE TITLE
⭐FEAT: Add animation the the developer cards 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/DevLeaders.github.io#10]
**Is your feature request related to a problem? Please describe.**
   The card should pop out displaying a card which has the following: 
   1. Youtube link
   2. Ig link 
   3. twitter link
   4. website of the creator
**Describe the solution you'd like**
Animation that pops out the a card

** Screenshots **
![Screenshot 2023-07-27 at 18-49-25 Dev Leaders](https://github.com/ArslanYM/dev-leaders/assets/104521101/fee3352a-9899-4e55-92fc-b8e8bc1fb27e)

**Comment by noorchauhan** [comment]
Assignment request:
Requesting to be assigned to work for this feature.

**Comment by ArslanYM** [comment]
@noorchauhan You can start working on this. Let me know if you need more context on this.

**Comment by noorchauhan** [comment]
> @noorchauhan You can start working on this. Let me know if you need more context on this.

On it
just need some basic ideas cleared:

1. The card should pop out or a overlay would work too?( If you have any examples I can look into)
2. What's the color schema for this section?

**Comment by ArslanYM** [comment]
An overlay would work , displaying the above said links etc. Cant really find an example. You can try your hand on the color schema. We havent yet decided a color schema for the project yet. You can start working on the basic for now.

**Comment by noorchauhan** [comment]
I have been working on this part, yet I feel I am not Design qualified enough to satisfy the basic idea of this, can I try other features for now and later catch on with this with betterment and let any other person try this for now, 
Thanks
