### ISSUE TITLE
⭐FEAT: Need documentation for the project (Docs)

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/DevLeaders.github.io#11]
**Is your feature request related to a problem? Please describe.**
This project needs little but necessary documents , they are 
1. CONTRIBUTING.md
2. CODE_OF_CONDUCT.md
3. README.md

**Describe the solution you'd like**
A clear and concise description of the contributing guidelines , code of conduct and readme for the project

**Comment by noorchauhan** [comment]
Assignment request:
Requesting to be assigned to work for this issue.
