### ISSUE TITLE
⭐FEAT: Add link to the github repository in the navbar 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/DevLeaders.github.io#6]
**Is your feature request related to a problem? Please describe.**
 Add link to the github repository in the navbar 

**Describe the solution you'd like**
Add github icon and the button should lead to the github repo
![Screenshot 2023-07-27 at 18-35-50 Dev Leaders](https://github.com/ArslanYM/dev-leaders/assets/104521101/37ad3171-1e64-41e6-873c-32e5de3c8550)

**Comment by AshwanthramKL** [comment]
Hey @ArslanYM, let me try my hand at this

**Comment by ArslanYM** [comment]
Letsgoo! @AshwanthramKL
