### ISSUE TITLE
⭐FEAT: Add logo in the navbar

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/DevLeaders.github.io#7]
**Is your feature request related to a problem? Please describe.**
  Create a logo for the app and add it in the navbar/footer

**Describe the solution you'd like**
Create prototypes first , when can proceed with the chosen one.

**Additional context**
![Screenshot 2023-07-27 at 18-38-30 Dev Leaders](https://github.com/ArslanYM/dev-leaders/assets/104521101/6341b385-47a9-49a1-88a9-daa8c2561347)

**Comment by simplysabir** [comment]
yo @ArslanYM , i think you can close this.
