### ISSUE TITLE
⭐FEAT: Add links in the navbar

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/DevLeaders.github.io#8]
**Is your feature request related to a problem? Please describe.**
 The first link should refer to `Home` , second to `Contributors`
**Describe the solution you'd like**
 Just change the names of first/second link in Navbar

**Screenshots**
![Screenshot 2023-07-27 at 18-38-30 Dev Leaders](https://github.com/ArslanYM/dev-leaders/assets/104521101/20032324-74c4-4aef-af20-cad33a0036ad)

**Comment by noorchauhan** [comment]
Assignment request:
Requesting to be assigned to work for this feature.

**Comment by ArslanYM** [comment]
Sure, You can start working on this. I will be assigning you the other issues as soon as you complete this one. Thanks.
