### ISSUE TITLE
⭐FEAT: Add a paragraph explaining the project 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/DevLeaders.github.io#9]
**Is your feature request related to a problem? Please describe.**
 Add a paragraph explaining the project 

**Describe the solution you'd like**
A clear and concise description of the project

**Additional context**
![Screenshot 2023-07-27 at 18-46-42 Dev Leaders](https://github.com/ArslanYM/dev-leaders/assets/104521101/65e34467-f13a-4f68-8cf5-930f7304c28a)

**Comment by simplysabir** [comment]
yo @ArslanYM , can i?

**Comment by ArslanYM** [comment]
Sure @simplysabir , Assigned to you

**Comment by simplysabir** [comment]
#16

**Comment by simplysabir** [comment]
#16 , raised a PR for it.
